spring:
  application:
    name: version-service

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:productcatalog}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin123}
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: version-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8090

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.bank.product.version: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# API Versioning Configuration
api:
  versioning:
    # Default versioning strategy
    default-strategy: URL_PATH

    # Default version if not specified
    default-version: v1

    # Supported versions
    supported-versions:
      - v1
      - v2

    # Deprecation policy
    deprecation:
      # Number of days before deprecated version is sunset
      sunset-days: 180

      # Number of days before sunset version is EOL
      eol-days: 90
