spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:mongodb}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:productcatalog}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

  kafka:
    bootstrap-servers: kafka:29092

server:
  port: 8090
