spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/product_catalog_db?authSource=admin

  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    com.bank.product.notification: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
