spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/product_catalog_db?authSource=admin

  kafka:
    bootstrap-servers: kafka:29092

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

# Temporal Configuration for Docker
temporal:
  connection:
    target: temporal:7233
  namespace: default

product:
  service:
    url: http://product-service:8081
    username: ${PRODUCT_SERVICE_USERNAME}
    password: ${PRODUCT_SERVICE_PASSWORD}

server:
  port: 8089

logging:
  level:
    root: INFO
    com.bank.product: INFO
    io.temporal: WARN
