spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/product_catalog_db?authSource=admin

  kafka:
    bootstrap-servers: kafka:29092

workflow:
  service:
    url: http://workflow-service:8089
    username: ${WORKFLOW_SERVICE_USERNAME}
    password: ${WORKFLOW_SERVICE_PASSWORD}

logging:
  level:
    com.bank.productcatalog: DEBUG
    org.springframework: INFO