spring:
  application:
    name: catalog-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${MONGODB_USERNAME:admin}:${MONGODB_PASSWORD:admin123}@localhost:27017/product_catalog_db?authSource=admin}
      auto-index-creation: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: catalog-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-change-this-in-production}
      expiration: 86400000

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.bank.productcatalog: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api:
  version: "1.0"
  title: "Product Catalog Service API"
  description: "API for managing product catalog"

app:
  versioning:
    supported-api-versions: "1.0"
    default-api-version: "1.0"
    supported-schema-versions: "1.0"
    default-schema-version: "1.0"
