spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@mongodb:27017/product_catalog_db?authSource=admin
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

# JWT Security Configuration
security:
  jwt:
    issuer: product-catalog-system
    algorithm: RS256
    access-token-expiration: PT15M    # 15 minutes
    refresh-token-expiration: P7D     # 7 days
    service-token-expiration: PT5M    # 5 minutes
    enable-blacklist: true
    blacklist-prefix: "jwt:blacklist:"

    # RSA Public Key for validating tokens (same as auth-service)
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzLecw0eDN9DcJ1K3/FfK
      qZveVvNWP7b8iNGG0onjEESLuTKxRVFbkM902256Gl15b1IBpyI594yzfL2hoJDN
      YIikbt5tqlai6izesYe/APoBOBZmAVvaPaL19iUYOIveI94LGK4p+PB5ZaAbmmn9
      EO4wx0ZJ/Ku7r+imvrArL/A149wYnrvGHgOJgjPXATJPzYMLFDyihzHf48spH0oi
      qxXiFNH15uPE8LIqGenpU15EbJp/3K3xEh+cN5ZoBKl8f5sUcg6nRrRybPBCoHC+
      klmZuV+Nl2lF3xgruRyGSJYoIWf93K7fXeDJOvF/sNzKLgtsGwhBEz0gUieeE4uu
      MQIDAQAB
      -----END PUBLIC KEY-----

services:
  auth-service:
    url: http://auth-service:8097
  product-service:
    url: http://product-service:8081
  workflow-service:
    url: http://workflow-service:8089
  party-service:
    url: http://party-service:8083
    timeout: 5000
  file-processing-service:
    url: http://file-processing-service:8094
  payment-service:
    url: http://payment-service:8095
  application-service:
    url: http://application-service:8096

logging:
  level:
    root: INFO
    com.bank.product.gateway: INFO
    org.springframework.cloud.gateway: INFO
