spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@mongodb:27017/product_catalog_db?authSource=admin
    redis:
      host: redis
      port: 6379
  
  kafka:
    bootstrap-servers: kafka:29092

services:
  product-service:
    url: http://product-service:8081
  workflow-service:
    url: http://workflow-service:8089
  party-service:
    url: http://party-service:8083
  file-processing-service:
    url: http://file-processing-service:8094
  payment-service:
    url: http://payment-service:8095
  application-service:
    url: http://application-service:8096

logging:
  level:
    root: INFO
    com.bank.product.gateway: INFO
    org.springframework.cloud.gateway: INFO
